/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assignment3.h"
#include <time.h>
#include <stdlib.h>
#include <stdio.h>
#include <dirent.h>
#include <string.h>


serverResponse *
get_date_and_time_1_svc(void *argp, struct svc_req *rqstp)
{
	static serverResponse  result_1;

	/*
	 * insert server code here
	 */
	printf("\nMessage from client: Send me the current time!\n");

	char* current_time_string;
	time_t current_time;

	current_time = time(NULL);
	if (current_time == ((time_t)-1)) {
		printf("Failure to obtain teh current time.\n");
		exit(EXIT_FAILURE);
	}
	current_time_string = ctime(&current_time);
	if (current_time_string == NULL) {
		printf("Failure to convert to current time.\n");
		exit(EXIT_FAILURE);
	}

	result_1.responseContent = current_time_string;

	


	return &result_1;
}

void swap(int* first, int* second) {
	int temp = *first;
	*first = *second;
	*second = temp;
}

int create_sorting_partition(int arr[], int low, int high) {
	int pivot = arr[high];
	int i = low -1;
	int j;
	for(j= low; j<=high-1; j++) {
		if (arr[j]<pivot) {
			i++;
			swap(&arr[i], &arr[j]);
		}
	}
	swap(&arr[i+1], &arr[high]);
	
	return (i+1);
}

void quickSortList(int arrayToBeSroted[], int low, int high) {
	if (low<high) {
		int pi = create_sorting_partition(arrayToBeSroted, low, high);

		quickSortList(arrayToBeSroted, low, pi-1);
		quickSortList(arrayToBeSroted, pi+1, high);
	}
}


serverResponse *
sort_list_integers_1_svc(serverResponse *argp, struct svc_req *rqstp)
{
	static serverResponse  result_2;

	/*
	 * insert server code here
	 */
	printf("\nMessage from client: Sort the following list: %s!\n", argp->responseContent);

	char receivedFromClient1[2000];
	strcpy(receivedFromClient1, argp->responseContent);
	char receivedFromClient2[2000];
	strcpy(receivedFromClient2, argp->responseContent);

	int i;
	int sizeOfArray = 0;
	char delim[] = " ";

	char *ptr1 = strtok(receivedFromClient1, delim);

	i=0;
	while(ptr1 != NULL)
	{
		sizeOfArray++;
		ptr1 = strtok(NULL, delim);
	}
		
	int listOfIntegers[sizeOfArray];

	char *ptr2 = strtok(receivedFromClient2, delim);
	
	i=0;
	while(ptr2 != NULL)
	{
		listOfIntegers[i] = atoi(ptr2);
		ptr2 = strtok(NULL, delim);
		i++;
	}

	int n = sizeof(listOfIntegers)/sizeof(listOfIntegers[0]);
	quickSortList(listOfIntegers, 0, n-1);

	char build_list[2000];
	build_list[0] = '\0';

	for (i=0; i<sizeOfArray; i++) {
		char buffer[5];
		sprintf(buffer, "%d ", listOfIntegers[i]);
		strcat(build_list, buffer);
		buffer[0] = '\0';
	}

	result_2.responseContent = build_list;
	return &result_2;
}

serverResponse *
list_of_files_current_folder_1_svc(void *argp, struct svc_req *rqstp)
{
	static serverResponse  result_3;

	/*
	 * insert server code here
	 */
	printf("\nMessage from client: Send me the list of files on the server!\n");

	
	char build_list[2000];

	DIR *d;
    	struct dirent *dir;
    	d = opendir(".");
   	if (d)
    	{
		build_list[0] = '\0';
        		while ((dir = readdir(d)) != NULL)
        		{
			char* file = dir->d_name;
			char* space = " ";
            		strcat(build_list, file);
			strcat(build_list, space);
        		}
        		closedir(d);
    	}

	result_3.responseContent = build_list;
	
	return &result_3;
}

serverResponse *
matrix_multiply_1_svc(serverResponse *argp, struct svc_req *rqstp)
{
	static serverResponse  result_4;

	/*
	 * insert server code here
	 */

	return &result_4;
}

serverResponse *
reverse_encryption_1_svc(serverResponse *argp, struct svc_req *rqstp)
{
	static serverResponse  result_5;

	/*
	 * insert server code here
	 */

	printf("\nString received: %s\n", argp->responseContent);
	char receivedFromClient[2000];
	strcpy(receivedFromClient, argp->responseContent);

	int stringLength = strlen(argp->responseContent);
	printf("\nString Lenght = %d\n", stringLength);
	int i,j;
	char temp;
	i=0;
	j=stringLength-1;
	printf("\nReceivde from client = %s\n", receivedFromClient);
	while (i<=((stringLength/2)-1)) {
		temp = receivedFromClient[i];
		receivedFromClient[i] = receivedFromClient[j];
		receivedFromClient[j] = temp;
		i++;
		j--;
	}
	printf("\nReverted String: %s\n", receivedFromClient);		

	result_5.responseContent = receivedFromClient;

	return &result_5;
}
