/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assignment3.h"
#include <stdio.h>
#include <stdlib.h>

char* readListOfIntegers() {
	int sizeOfList,i;
	printf("\nInput the size of the list of integers: ");
	scanf("%d", &sizeOfList);
	int listOfIntegers[sizeOfList];
	
	char build_list[2000];
	
	build_list[0] = '\0';

	for (i=0; i<sizeOfList; i++) {
		char buffer[5];
		printf("\nelement[%d] = ",i);
		scanf("%d", &listOfIntegers[i]);
		sprintf(buffer, "%d ", listOfIntegers[i]);
		strcat(build_list, buffer);
		buffer[0] = '\0';
	}
	
	printf("\nbuild list = %s\n", build_list);
	

	return build_list;
}

void
assignment3_1(char *host)
{
	CLIENT *clnt;
	serverResponse  *result_1;
	char *get_date_and_time_1_arg;
	serverResponse  *result_2;
	serverResponse  sort_list_integers_1_arg;
	serverResponse  *result_3;
	char *list_of_files_current_folder_1_arg;
	serverResponse  *result_4;
	serverResponse  matrix_multiply_1_arg;
	serverResponse  *result_5;
	serverResponse  reverse_encryption_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ASSIGNMENT3, ASSIGNMENT3_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = get_date_and_time_1((void*)&get_date_and_time_1_arg, clnt);
	if (result_1 == (serverResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("\nCurrent time is: %s\n", result_1->responseContent);
	}
	
	sort_list_integers_1_arg.responseContent = readListOfIntegers();
	printf("\nReceived input list = %s\n", sort_list_integers_1_arg.responseContent);
	result_2 = sort_list_integers_1(&sort_list_integers_1_arg, clnt);
	if (result_2 == (serverResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("\nSorted List is: %s\n", result_2->responseContent);
	}


	result_3 = list_of_files_current_folder_1((void*)&list_of_files_current_folder_1_arg, clnt);
	if (result_3 == (serverResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("\nThe list of files on current folder on server is: %s\n", result_3->responseContent);
	}


	result_4 = matrix_multiply_1(&matrix_multiply_1_arg, clnt);
	if (result_4 == (serverResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	char string[2000];
	printf("\nInput the string to be reversed: ");
	getchar();
	fgets(string, 2000, stdin);
	reverse_encryption_1_arg.responseContent = string;
	result_5 = reverse_encryption_1(&reverse_encryption_1_arg, clnt);
	if (result_5 == (serverResponse *) NULL) {
		clnt_perror (clnt, "call failed");
	} else {
		printf("\nThe reversed encrypted string received is: %s\n", result_5->responseContent);
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	assignment3_1 (host);
exit (0);
}
